[package]
name = "npm_time_machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.8"
reqwest = { version = "0.11.14", features = ["json"] }
semver = "1.0.17"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
time = { version = "0.3.20", features = ["macros", "parsing"] }
tokio = { version = "1.26.0", features = ["full"] }
